# =======================================================================
# File: ludus_join_child_domain/tasks/main.yml
# =======================================================================
---
- name: Validate required variables
  assert:
    that:
      - dns_domain_name is defined
      - child_domain_netbios_name is defined
      - dc_ip is defined
      - ad_domain_admin is defined
      - ad_domain_admin_password is defined
    fail_msg: "Missing required domain join variables."

- name: Wait for LDAP port {{ ldap_port }} to become available
  ansible.windows.win_wait_for:
    port: "{{ ldap_port }}"
    host: "{{ dc_ip }}"
    delay: "{{ ldap_delay }}"
    timeout: "{{ ldap_timeout }}"

- name: Join domain with retries
  ansible.windows.win_domain_membership:
    dns_domain_name: "{{ dns_domain_name }}"
    domain_admin_user: "{{ ad_domain_admin }}"
    domain_admin_password: "{{ ad_domain_admin_password }}"
    domain_ou_path: ""
    state: domain
  register: domain_join
  retries: "{{ join_retries }}"
  delay: "{{ join_delay }}"
  until: domain_join is succeeded
  check_mode: no

- name: Reboot after domain join
  ansible.windows.win_reboot:
    reboot_timeout: 600
  when: domain_join.changed

- name: Install RSAT tools (Server OS only)
  ansible.windows.win_feature:
    name: RSAT-AD-PowerShell
    state: present
  when:
    - install_rsat
    - ansible_facts.os_family == "Windows"
    - "'Server' in ansible_facts.product_name"
