# =======================================================================
# File: ludus_verify_dc_ready/tasks/main.yml
# Description: This task file acts as a readiness probe for a Domain
#              Controller. It is used as a dependency check to ensure
#              a DC's services are available before other roles attempt
#              to interact with it.
# =======================================================================
---
- name: Wait for Domain Controller LDAP port ({{ ldap_port }}) to become available
  ansible.windows.win_wait_for:
    # The port to check for. LDAP (389) is a reliable indicator
    # that Active Directory Domain Services are running.
    port: "{{ ldap_port }}"

    # Use 'ansible_host' which is the IP from the inventory that Ansible
    # is connecting to. This is more reliable than 'ansible_default_ipv4'
    # which depends on fact gathering that may not have completed.
    host: "{{ ansible_host }}"

    # Delay before starting the check. This gives services time to
    # initialize after a reboot.
    delay: "{{ ldap_delay }}"

    # The maximum time to wait for the port to become available.
    timeout: "{{ ldap_timeout }}"
