# =======================================================================
# File: ludus_verify_dc_ready/tasks/main.yml
# =======================================================================
---
- name: Wait for LDAP port {{ ldap_port }} to become available
  ansible.windows.win_wait_for:
    port: "{{ ldap_port }}"
    host: "{{ ansible_default_ipv4.address }}"
    delay: "{{ ldap_delay }}"
    timeout: "{{ ldap_timeout }}"
  register: ldap_check

- name: Debug LDAP readiness result
  debug:
    var: ldap_check
