# =======================================================================
# File: ludus_verify_dc_ready/tasks/main.yml
# =======================================================================
---
- name: Wait for the Domain Controller to be ready for authentication
  ansible.windows.win_wait_for:
    # Uses the IP address Ansible is using for the current host.
    host: "{{ ansible_host }}"
    port: 389 # Standard LDAP port, indicates AD services are running.
    timeout: 300 # Wait for up to 5 minutes.
  # This check is run from the Ludus controller for reliability.
  delegate_to: localhost
